import type { AIAgentDefinition } from './types';

export const BUILT_IN_AI_AGENTS: AIAgentDefinition[] = [
  {
    type: 'general-purpose',
    displayName: '通用执行 Agent',
    description: '通用多步骤任务、代码分析、实现与排查。',
    whenToUse: '用于复杂实现、修复、重构、排查等需要多轮工具调用的任务。',
    systemPrompt: '你是通用执行 Agent，负责处理复杂多步骤任务。需要先理解上下文，再使用可用工具完成任务，并给出清晰结果。',
    tools: ['*'],
    model: 'inherit',
    mode: 'execute',
    source: 'built-in',
  },
  {
    type: 'explore',
    displayName: '源码探索 Agent',
    description: '只读搜索、源码学习、调用链梳理、机制分析。',
    whenToUse: '用于学习源码、梳理调用链、定位实现、分析机制等只读研究任务。',
    systemPrompt: '你是只读探索 Agent。只能读取、搜索和分析信息，不要修改文件或执行破坏性操作。输出应包含关键发现和证据位置。',
    tools: ['read-file', 'search-files', 'list-files'],
    disallowedTools: ['write-file', 'apply-patch', 'delete-file'],
    model: 'fast',
    mode: 'read-only',
    source: 'built-in',
  },
  {
    type: 'plan',
    displayName: '方案规划 Agent',
    description: '设计实现方案、架构方案、执行计划，适合先确认后执行的任务。',
    whenToUse: '用于先输出方案、架构设计、改造计划、风险评估和确认后执行的任务。',
    systemPrompt: '你是规划 Agent。基于现有上下文输出可执行方案、风险点和验证方式。除非明确要求，不要修改文件。',
    tools: ['read-file', 'search-files', 'list-files'],
    disallowedTools: ['write-file', 'apply-patch', 'delete-file'],
    model: 'inherit',
    mode: 'plan',
    source: 'built-in',
  },
  {
    type: 'verifier',
    displayName: '验证 Agent',
    description: '对实现结果进行独立验证，检查测试、边界条件和潜在回归。',
    whenToUse: '用于实现完成后的独立验证、运行检查、确认边界条件和回归风险。',
    systemPrompt: '你是验证 Agent。独立检查实现结果是否满足目标，优先运行或建议最相关的验证步骤。不要修改项目文件。最终输出应包含 VERDICT: PASS、VERDICT: FAIL 或 VERDICT: PARTIAL。',
    tools: ['read-file', 'search-files', 'list-files', 'run-check'],
    disallowedTools: ['write-file', 'apply-patch', 'delete-file'],
    model: 'inherit',
    mode: 'verify',
    background: true,
    source: 'built-in',
  },
  {
    type: 'runtime-guide',
    displayName: 'Runtime 指南 Agent',
    description: '解释当前 agent runtime、配置、工具和调度机制。',
    whenToUse: '用于解释 AI Runtime、Agent、工具、权限、调度和配置相关问题。',
    systemPrompt: '你是 Runtime Guide Agent，负责解释 agent/runtime 配置、工具能力、调度策略和使用方式。',
    tools: ['read-file', 'search-files', 'list-files'],
    model: 'fast',
    mode: 'read-only',
    source: 'built-in',
  },
];

export const getBuiltInAIAgents = (): AIAgentDefinition[] => BUILT_IN_AI_AGENTS.map((agent) => ({ ...agent }));
